import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'staging', 'production').default('development'),
  PORT: Joi.number().default(3000),
  DATABASE_URL: Joi.string().required(),
  JWT_SECRET: Joi.string().min(32).required(),
  JWT_EXPIRES_IN: Joi.string().default('7d'),
  FRONTEND_URL: Joi.string().default('http://localhost:5173'),
  TWILIO_ACCOUNT_SID: Joi.string().optional().allow(''),
  TWILIO_AUTH_TOKEN: Joi.string().optional().allow(''),
  TWILIO_WHATSAPP_NUMBER: Joi.string().optional().allow(''),
  TWILIO_ENV: Joi.string().valid('sandbox', 'production').default('sandbox'),
  WOMPI_BASE_URL: Joi.string().optional().allow(''),
  WOMPI_EVENTS_SECRET: Joi.string().optional().allow(''),
  WOMPI_PUBLIC_KEY: Joi.string().optional().allow(''),
  AI_SERVICE_URL: Joi.string().optional().allow(''),
  SMTP_HOST: Joi.string().optional().allow(''),
  SMTP_PORT: Joi.number().default(587),
  SMTP_SECURE: Joi.string().default('false'),
  SMTP_USER: Joi.string().optional().allow(''),
  SMTP_PASS: Joi.string().optional().allow(''),
  SMTP_FROM: Joi.string().optional().allow(''),
  ANTHROPIC_API_KEY: Joi.string().optional().allow(''),
  VAPID_PUBLIC_KEY: Joi.string().optional().allow(''),
  VAPID_PRIVATE_KEY: Joi.string().optional().allow(''),
  VAPID_EMAIL: Joi.string().optional().allow(''),
  SUPERADMIN_EMAIL: Joi.string().email().optional().allow(''),
  SUPERADMIN_PASSWORD: Joi.string().optional().allow(''),
  INTERNAL_API_KEY: Joi.string().min(16).optional().allow(''),
  SENTRY_DSN: Joi.string().optional().allow(''),
});
