-- Índices para consultas multi-tenant y claves foráneas calientes
CREATE INDEX IF NOT EXISTS "User_tenantId_idx" ON "User"("tenantId");
CREATE INDEX IF NOT EXISTS "PasswordResetToken_userId_idx" ON "PasswordResetToken"("userId");
CREATE INDEX IF NOT EXISTS "RefreshToken_userId_idx" ON "RefreshToken"("userId");
CREATE INDEX IF NOT EXISTS "Order_tenantId_createdAt_idx" ON "Order"("tenantId", "createdAt");
CREATE INDEX IF NOT EXISTS "OrderItem_orderId_idx" ON "OrderItem"("orderId");
CREATE INDEX IF NOT EXISTS "Product_tenantId_idx" ON "Product"("tenantId");
CREATE INDEX IF NOT EXISTS "Ticket_tenantId_createdAt_idx" ON "Ticket"("tenantId", "createdAt");
CREATE INDEX IF NOT EXISTS "Cotizacion_tenantId_idx" ON "Cotizacion"("tenantId");
CREATE INDEX IF NOT EXISTS "CotizacionItem_cotizacionId_idx" ON "CotizacionItem"("cotizacionId");
CREATE INDEX IF NOT EXISTS "Notificacion_tenantId_createdAt_idx" ON "Notificacion"("tenantId", "createdAt");
CREATE INDEX IF NOT EXISTS "SupplierProduct_supplierId_idx" ON "SupplierProduct"("supplierId");
CREATE INDEX IF NOT EXISTS "MenuDia_tenantId_fecha_idx" ON "MenuDia"("tenantId", "fecha");
CREATE INDEX IF NOT EXISTS "PlatoMenuDia_menuDiaId_idx" ON "PlatoMenuDia"("menuDiaId");
CREATE INDEX IF NOT EXISTS "Professional_tenantId_idx" ON "Professional"("tenantId");
CREATE INDEX IF NOT EXISTS "Schedule_professionalId_idx" ON "Schedule"("professionalId");
CREATE INDEX IF NOT EXISTS "Service_tenantId_idx" ON "Service"("tenantId");
CREATE INDEX IF NOT EXISTS "Appointment_tenantId_date_idx" ON "Appointment"("tenantId", "date");
CREATE INDEX IF NOT EXISTS "Conversation_tenantId_lastMessageAt_idx" ON "Conversation"("tenantId", "lastMessageAt");
CREATE INDEX IF NOT EXISTS "Message_conversationId_createdAt_idx" ON "Message"("conversationId", "createdAt");
CREATE INDEX IF NOT EXISTS "HazloRequest_tenantId_idx" ON "HazloRequest"("tenantId");
CREATE INDEX IF NOT EXISTS "ApiKey_tenantId_idx" ON "ApiKey"("tenantId");
CREATE INDEX IF NOT EXISTS "PaymentIntent_tenantId_idx" ON "PaymentIntent"("tenantId");
CREATE INDEX IF NOT EXISTS "Gasto_tenantId_fecha_idx" ON "Gasto"("tenantId", "fecha");
CREATE INDEX IF NOT EXISTS "Campaña_tenantId_idx" ON "Campaña"("tenantId");
CREATE INDEX IF NOT EXISTS "Automacion_tenantId_idx" ON "Automacion"("tenantId");
CREATE INDEX IF NOT EXISTS "AutomacionPaso_automacionId_idx" ON "AutomacionPaso"("automacionId");
CREATE INDEX IF NOT EXISTS "AutomacionEjecucion_tenantId_idx" ON "AutomacionEjecucion"("tenantId");
CREATE INDEX IF NOT EXISTS "AutomacionEjecucion_status_scheduledAt_idx" ON "AutomacionEjecucion"("status", "scheduledAt");
CREATE INDEX IF NOT EXISTS "Garantia_tenantId_idx" ON "Garantia"("tenantId");
CREATE INDEX IF NOT EXISTS "Resena_tenantId_createdAt_idx" ON "Resena"("tenantId", "createdAt");
CREATE INDEX IF NOT EXISTS "Proveedor_tenantId_idx" ON "Proveedor"("tenantId");
CREATE INDEX IF NOT EXISTS "OrdenCompra_tenantId_idx" ON "OrdenCompra"("tenantId");
CREATE INDEX IF NOT EXISTS "OrdenCompraItem_ordenCompraId_idx" ON "OrdenCompraItem"("ordenCompraId");
CREATE INDEX IF NOT EXISTS "PushSubscription_tenantId_idx" ON "PushSubscription"("tenantId");
CREATE INDEX IF NOT EXISTS "Turno_tenantId_fecha_idx" ON "Turno"("tenantId", "fecha");
CREATE INDEX IF NOT EXISTS "NpsRespuesta_tenantId_idx" ON "NpsRespuesta"("tenantId");
CREATE INDEX IF NOT EXISTS "Sucursal_tenantId_idx" ON "Sucursal"("tenantId");
CREATE INDEX IF NOT EXISTS "TallaConfig_tenantId_idx" ON "TallaConfig"("tenantId");
CREATE INDEX IF NOT EXISTS "TallaConsulta_tenantId_idx" ON "TallaConsulta"("tenantId");
CREATE INDEX IF NOT EXISTS "PagoRegistro_tenantId_createdAt_idx" ON "PagoRegistro"("tenantId", "createdAt");
